/* The following code was generated by JFlex 1.4.3 on 20/05/19 19:59 */

package AnaliseLexica;

import static AnaliseLexica.Token.*;


/**
 * This class is a scanner generated by 
 * <a href="http://www.jflex.de/">JFlex</a> 1.4.3
 * on 20/05/19 19:59 from the specification file
 * <tt>C:/Users/12161003841/Desktop/Compiladores/ClusterV8/src/AnaliseLexica/Lexer.flex</tt>
 */
class Lexer {

  /** This character denotes the end of file */
  public static final int YYEOF = -1;

  /** initial size of the lookahead buffer */
  private static final int ZZ_BUFFERSIZE = 16384;

  /** lexical states */
  public static final int YYINITIAL = 0;

  /**
   * ZZ_LEXSTATE[l] is the state in the DFA for the lexical state l
   * ZZ_LEXSTATE[l+1] is the state in the DFA for the lexical state l
   *                  at the beginning of a line
   * l is of the form l = 2*k, k a non negative integer
   */
  private static final int ZZ_LEXSTATE[] = { 
     0, 0
  };

  /** 
   * Translates characters to character classes
   */
  private static final String ZZ_CMAP_PACKED = 
    "\11\0\1\3\1\4\2\0\1\3\22\0\1\3\1\43\1\0\1\60"+
    "\1\11\1\0\1\44\1\0\1\32\1\33\1\7\1\41\1\57\1\42"+
    "\1\15\1\41\12\1\2\0\1\10\1\40\1\6\1\5\1\55\4\2"+
    "\1\52\2\2\1\47\1\50\2\2\1\51\12\2\1\46\3\2\1\36"+
    "\1\0\1\37\1\41\2\0\1\12\1\16\1\22\1\56\1\21\1\20"+
    "\1\24\1\23\1\17\4\2\1\31\1\53\1\26\1\14\1\13\1\30"+
    "\1\27\1\54\1\25\4\2\1\34\1\45\1\35\uff82\0";

  /** 
   * Translates characters to character classes
   */
  private static final char [] ZZ_CMAP = zzUnpackCMap(ZZ_CMAP_PACKED);

  /** 
   * Translates DFA states to action switch labels.
   */
  private static final int [] ZZ_ACTION = zzUnpackAction();

  private static final String ZZ_ACTION_PACKED_0 =
    "\1\1\1\2\1\1\1\3\1\4\1\2\1\5\1\6"+
    "\1\5\6\2\1\7\1\10\1\11\1\12\1\13\1\14"+
    "\1\15\1\6\1\5\4\2\1\16\1\17\1\20\3\0"+
    "\1\21\1\0\1\22\2\0\1\23\1\24\1\0\1\25"+
    "\1\26\1\27\2\0\1\16\2\0\1\30\1\31\2\22"+
    "\6\0\1\32\1\0\1\33\1\0\1\34\2\0\1\35"+
    "\2\0\1\36\1\0\1\34\5\0\1\37\1\40\3\0"+
    "\1\41\11\0\1\42\1\43";

  private static int [] zzUnpackAction() {
    int [] result = new int[95];
    int offset = 0;
    offset = zzUnpackAction(ZZ_ACTION_PACKED_0, offset, result);
    return result;
  }

  private static int zzUnpackAction(String packed, int offset, int [] result) {
    int i = 0;       /* index in packed string  */
    int j = offset;  /* index in unpacked array */
    int l = packed.length();
    while (i < l) {
      int count = packed.charAt(i++);
      int value = packed.charAt(i++);
      do result[j++] = value; while (--count > 0);
    }
    return j;
  }


  /** 
   * Translates a state to a row index in the transition table
   */
  private static final int [] ZZ_ROWMAP = zzUnpackRowMap();

  private static final String ZZ_ROWMAP_PACKED_0 =
    "\0\0\0\61\0\142\0\61\0\61\0\223\0\304\0\61"+
    "\0\365\0\u0126\0\u0157\0\u0188\0\u01b9\0\u01ea\0\u021b\0\61"+
    "\0\61\0\61\0\61\0\61\0\61\0\u024c\0\u027d\0\61"+
    "\0\u02ae\0\u02df\0\u0310\0\u0341\0\u0372\0\61\0\61\0\u03a3"+
    "\0\u03d4\0\u0405\0\61\0\u0436\0\u0467\0\u0498\0\u04c9\0\u04fa"+
    "\0\u052b\0\u055c\0\u058d\0\61\0\61\0\u05be\0\u05ef\0\u0620"+
    "\0\u0651\0\u0682\0\61\0\61\0\61\0\u06b3\0\u06e4\0\u0715"+
    "\0\u0746\0\u0777\0\u07a8\0\u07d9\0\61\0\u080a\0\61\0\u083b"+
    "\0\u0651\0\u086c\0\u089d\0\61\0\u08ce\0\u08ff\0\61\0\u0930"+
    "\0\61\0\u0961\0\u0992\0\u09c3\0\u09f4\0\u0a25\0\61\0\61"+
    "\0\u0a56\0\u0a87\0\u0ab8\0\61\0\u0ae9\0\u0b1a\0\u0b4b\0\u0b7c"+
    "\0\u0bad\0\u0bde\0\u0c0f\0\u0c40\0\u0c71\0\61\0\61";

  private static int [] zzUnpackRowMap() {
    int [] result = new int[95];
    int offset = 0;
    offset = zzUnpackRowMap(ZZ_ROWMAP_PACKED_0, offset, result);
    return result;
  }

  private static int zzUnpackRowMap(String packed, int offset, int [] result) {
    int i = 0;  /* index in packed string  */
    int j = offset;  /* index in unpacked array */
    int l = packed.length();
    while (i < l) {
      int high = packed.charAt(i++) << 16;
      result[j++] = high | packed.charAt(i++);
    }
    return j;
  }

  /** 
   * The transition table of the DFA
   */
  private static final int [] ZZ_TRANS = zzUnpackTrans();

  private static final String ZZ_TRANS_PACKED_0 =
    "\1\2\1\3\1\2\1\4\1\5\1\6\1\7\1\10"+
    "\1\11\1\12\1\13\1\14\3\2\1\15\1\16\7\2"+
    "\1\17\1\2\1\20\1\21\1\22\1\23\1\24\1\25"+
    "\1\26\1\10\1\27\1\30\1\31\1\32\1\33\4\2"+
    "\1\34\1\2\1\35\1\2\1\36\1\37\62\0\1\3"+
    "\65\0\1\40\60\0\1\41\31\0\1\30\30\0\1\42"+
    "\27\0\1\30\1\0\1\43\16\0\7\44\1\0\1\44"+
    "\1\45\47\44\13\0\1\46\66\0\1\47\70\0\1\50"+
    "\24\0\1\51\21\0\1\52\62\0\1\53\77\0\1\30"+
    "\26\0\1\54\116\0\1\55\61\0\1\55\62\0\1\56"+
    "\65\0\1\57\5\0\1\60\1\35\7\0\3\35\1\0"+
    "\14\35\14\0\7\35\1\0\1\35\2\0\7\61\1\0"+
    "\1\62\50\61\6\0\1\63\62\0\1\64\50\0\11\44"+
    "\1\65\60\44\1\66\47\44\14\0\1\67\72\0\1\70"+
    "\51\0\1\71\7\0\1\72\32\0\1\51\110\0\1\73"+
    "\55\0\1\74\2\0\1\75\77\0\1\76\37\0\1\77"+
    "\32\0\1\60\57\0\10\61\1\100\55\61\1\101\2\61"+
    "\1\100\50\61\11\0\1\66\64\0\1\102\64\0\1\103"+
    "\66\0\1\104\52\0\1\105\56\0\1\106\53\0\1\107"+
    "\117\0\1\110\7\0\5\61\1\111\2\61\1\100\50\61"+
    "\12\0\1\112\5\0\1\113\3\0\1\114\46\0\1\115"+
    "\61\0\1\116\74\0\1\117\103\0\1\120\24\0\1\121"+
    "\63\0\1\122\52\0\1\123\74\0\1\124\44\0\1\125"+
    "\60\0\1\126\67\0\1\127\50\0\1\130\122\0\1\131"+
    "\23\0\1\132\64\0\1\133\62\0\1\134\61\0\1\135"+
    "\45\0\1\136\57\0\1\132\67\0\1\132\66\0\1\137"+
    "\31\0";

  private static int [] zzUnpackTrans() {
    int [] result = new int[3234];
    int offset = 0;
    offset = zzUnpackTrans(ZZ_TRANS_PACKED_0, offset, result);
    return result;
  }

  private static int zzUnpackTrans(String packed, int offset, int [] result) {
    int i = 0;       /* index in packed string  */
    int j = offset;  /* index in unpacked array */
    int l = packed.length();
    while (i < l) {
      int count = packed.charAt(i++);
      int value = packed.charAt(i++);
      value--;
      do result[j++] = value; while (--count > 0);
    }
    return j;
  }


  /* error codes */
  private static final int ZZ_UNKNOWN_ERROR = 0;
  private static final int ZZ_NO_MATCH = 1;
  private static final int ZZ_PUSHBACK_2BIG = 2;

  /* error messages for the codes above */
  private static final String ZZ_ERROR_MSG[] = {
    "Unkown internal scanner error",
    "Error: could not match input",
    "Error: pushback value was too large"
  };

  /**
   * ZZ_ATTRIBUTE[aState] contains the attributes of state <code>aState</code>
   */
  private static final int [] ZZ_ATTRIBUTE = zzUnpackAttribute();

  private static final String ZZ_ATTRIBUTE_PACKED_0 =
    "\1\1\1\11\1\1\2\11\2\1\1\11\7\1\6\11"+
    "\2\1\1\11\5\1\2\11\3\0\1\11\1\0\1\1"+
    "\2\0\2\1\1\0\1\1\2\11\2\0\1\1\2\0"+
    "\3\11\1\1\6\0\1\11\1\0\1\11\1\0\1\1"+
    "\2\0\1\11\2\0\1\11\1\0\1\11\5\0\2\11"+
    "\3\0\1\11\11\0\2\11";

  private static int [] zzUnpackAttribute() {
    int [] result = new int[95];
    int offset = 0;
    offset = zzUnpackAttribute(ZZ_ATTRIBUTE_PACKED_0, offset, result);
    return result;
  }

  private static int zzUnpackAttribute(String packed, int offset, int [] result) {
    int i = 0;       /* index in packed string  */
    int j = offset;  /* index in unpacked array */
    int l = packed.length();
    while (i < l) {
      int count = packed.charAt(i++);
      int value = packed.charAt(i++);
      do result[j++] = value; while (--count > 0);
    }
    return j;
  }

  /** the input device */
  private java.io.Reader zzReader;

  /** the current state of the DFA */
  private int zzState;

  /** the current lexical state */
  private int zzLexicalState = YYINITIAL;

  /** this buffer contains the current text to be matched and is
      the source of the yytext() string */
  private char zzBuffer[] = new char[ZZ_BUFFERSIZE];

  /** the textposition at the last accepting state */
  private int zzMarkedPos;

  /** the current text position in the buffer */
  private int zzCurrentPos;

  /** startRead marks the beginning of the yytext() string in the buffer */
  private int zzStartRead;

  /** endRead marks the last character in the buffer, that has been read
      from input */
  private int zzEndRead;

  /** number of newlines encountered up to the start of the matched text */
  private int yyline;

  /** the number of characters up to the start of the matched text */
  private int yychar;

  /**
   * the number of characters from the last newline up to the start of the 
   * matched text
   */
  private int yycolumn;

  /** 
   * zzAtBOL == true <=> the scanner is currently at the beginning of a line
   */
  private boolean zzAtBOL = true;

  /** zzAtEOF == true <=> the scanner is at the EOF */
  private boolean zzAtEOF;

  /** denotes if the user-EOF-code has already been executed */
  private boolean zzEOFDone;

  /* user code: */
public String lexeme;


  /**
   * Creates a new scanner
   * There is also a java.io.InputStream version of this constructor.
   *
   * @param   in  the java.io.Reader to read input from.
   */
  Lexer(java.io.Reader in) {
    this.zzReader = in;
  }

  /**
   * Creates a new scanner.
   * There is also java.io.Reader version of this constructor.
   *
   * @param   in  the java.io.Inputstream to read input from.
   */
  Lexer(java.io.InputStream in) {
    this(new java.io.InputStreamReader(in));
  }

  /** 
   * Unpacks the compressed character translation table.
   *
   * @param packed   the packed character translation table
   * @return         the unpacked character translation table
   */
  private static char [] zzUnpackCMap(String packed) {
    char [] map = new char[0x10000];
    int i = 0;  /* index in packed string  */
    int j = 0;  /* index in unpacked array */
    while (i < 136) {
      int  count = packed.charAt(i++);
      char value = packed.charAt(i++);
      do map[j++] = value; while (--count > 0);
    }
    return map;
  }


  /**
   * Refills the input buffer.
   *
   * @return      <code>false</code>, iff there was new input.
   * 
   * @exception   java.io.IOException  if any I/O-Error occurs
   */
  private boolean zzRefill() throws java.io.IOException {

    /* first: make room (if you can) */
    if (zzStartRead > 0) {
      System.arraycopy(zzBuffer, zzStartRead,
                       zzBuffer, 0,
                       zzEndRead-zzStartRead);

      /* translate stored positions */
      zzEndRead-= zzStartRead;
      zzCurrentPos-= zzStartRead;
      zzMarkedPos-= zzStartRead;
      zzStartRead = 0;
    }

    /* is the buffer big enough? */
    if (zzCurrentPos >= zzBuffer.length) {
      /* if not: blow it up */
      char newBuffer[] = new char[zzCurrentPos*2];
      System.arraycopy(zzBuffer, 0, newBuffer, 0, zzBuffer.length);
      zzBuffer = newBuffer;
    }

    /* finally: fill the buffer with new input */
    int numRead = zzReader.read(zzBuffer, zzEndRead,
                                            zzBuffer.length-zzEndRead);

    if (numRead > 0) {
      zzEndRead+= numRead;
      return false;
    }
    // unlikely but not impossible: read 0 characters, but not at end of stream    
    if (numRead == 0) {
      int c = zzReader.read();
      if (c == -1) {
        return true;
      } else {
        zzBuffer[zzEndRead++] = (char) c;
        return false;
      }     
    }

	// numRead < 0
    return true;
  }

    
  /**
   * Closes the input stream.
   */
  public final void yyclose() throws java.io.IOException {
    zzAtEOF = true;            /* indicate end of file */
    zzEndRead = zzStartRead;  /* invalidate buffer    */

    if (zzReader != null)
      zzReader.close();
  }


  /**
   * Resets the scanner to read from a new input stream.
   * Does not close the old reader.
   *
   * All internal variables are reset, the old input stream 
   * <b>cannot</b> be reused (internal buffer is discarded and lost).
   * Lexical state is set to <tt>ZZ_INITIAL</tt>.
   *
   * @param reader   the new input stream 
   */
  public final void yyreset(java.io.Reader reader) {
    zzReader = reader;
    zzAtBOL  = true;
    zzAtEOF  = false;
    zzEOFDone = false;
    zzEndRead = zzStartRead = 0;
    zzCurrentPos = zzMarkedPos = 0;
    yyline = yychar = yycolumn = 0;
    zzLexicalState = YYINITIAL;
  }


  /**
   * Returns the current lexical state.
   */
  public final int yystate() {
    return zzLexicalState;
  }


  /**
   * Enters a new lexical state
   *
   * @param newState the new lexical state
   */
  public final void yybegin(int newState) {
    zzLexicalState = newState;
  }


  /**
   * Returns the text matched by the current regular expression.
   */
  public final String yytext() {
    return new String( zzBuffer, zzStartRead, zzMarkedPos-zzStartRead );
  }


  /**
   * Returns the character at position <tt>pos</tt> from the 
   * matched text. 
   * 
   * It is equivalent to yytext().charAt(pos), but faster
   *
   * @param pos the position of the character to fetch. 
   *            A value from 0 to yylength()-1.
   *
   * @return the character at position pos
   */
  public final char yycharat(int pos) {
    return zzBuffer[zzStartRead+pos];
  }


  /**
   * Returns the length of the matched text region.
   */
  public final int yylength() {
    return zzMarkedPos-zzStartRead;
  }


  /**
   * Reports an error that occured while scanning.
   *
   * In a wellformed scanner (no or only correct usage of 
   * yypushback(int) and a match-all fallback rule) this method 
   * will only be called with things that "Can't Possibly Happen".
   * If this method is called, something is seriously wrong
   * (e.g. a JFlex bug producing a faulty scanner etc.).
   *
   * Usual syntax/scanner level error handling should be done
   * in error fallback rules.
   *
   * @param   errorCode  the code of the errormessage to display
   */
  private void zzScanError(int errorCode) {
    String message;
    try {
      message = ZZ_ERROR_MSG[errorCode];
    }
    catch (ArrayIndexOutOfBoundsException e) {
      message = ZZ_ERROR_MSG[ZZ_UNKNOWN_ERROR];
    }

    throw new Error(message);
  } 


  /**
   * Pushes the specified amount of characters back into the input stream.
   *
   * They will be read again by then next call of the scanning method
   *
   * @param number  the number of characters to be read again.
   *                This number must not be greater than yylength()!
   */
  public void yypushback(int number)  {
    if ( number > yylength() )
      zzScanError(ZZ_PUSHBACK_2BIG);

    zzMarkedPos -= number;
  }


  /**
   * Resumes scanning until the next regular expression is matched,
   * the end of input is encountered or an I/O-Error occurs.
   *
   * @return      the next token
   * @exception   java.io.IOException  if any I/O-Error occurs
   */
  public Token yylex() throws java.io.IOException {
    int zzInput;
    int zzAction;

    // cached fields:
    int zzCurrentPosL;
    int zzMarkedPosL;
    int zzEndReadL = zzEndRead;
    char [] zzBufferL = zzBuffer;
    char [] zzCMapL = ZZ_CMAP;

    int [] zzTransL = ZZ_TRANS;
    int [] zzRowMapL = ZZ_ROWMAP;
    int [] zzAttrL = ZZ_ATTRIBUTE;

    while (true) {
      zzMarkedPosL = zzMarkedPos;

      zzAction = -1;

      zzCurrentPosL = zzCurrentPos = zzStartRead = zzMarkedPosL;
  
      zzState = ZZ_LEXSTATE[zzLexicalState];


      zzForAction: {
        while (true) {
    
          if (zzCurrentPosL < zzEndReadL)
            zzInput = zzBufferL[zzCurrentPosL++];
          else if (zzAtEOF) {
            zzInput = YYEOF;
            break zzForAction;
          }
          else {
            // store back cached positions
            zzCurrentPos  = zzCurrentPosL;
            zzMarkedPos   = zzMarkedPosL;
            boolean eof = zzRefill();
            // get translated positions and possibly new buffer
            zzCurrentPosL  = zzCurrentPos;
            zzMarkedPosL   = zzMarkedPos;
            zzBufferL      = zzBuffer;
            zzEndReadL     = zzEndRead;
            if (eof) {
              zzInput = YYEOF;
              break zzForAction;
            }
            else {
              zzInput = zzBufferL[zzCurrentPosL++];
            }
          }
          int zzNext = zzTransL[ zzRowMapL[zzState] + zzCMapL[zzInput] ];
          if (zzNext == -1) break zzForAction;
          zzState = zzNext;

          int zzAttributes = zzAttrL[zzState];
          if ( (zzAttributes & 1) == 1 ) {
            zzAction = zzState;
            zzMarkedPosL = zzCurrentPosL;
            if ( (zzAttributes & 8) == 8 ) break zzForAction;
          }

        }
      }

      // store back cached position
      zzMarkedPos = zzMarkedPosL;

      switch (zzAction < 0 ? zzAction : ZZ_ACTION[zzAction]) {
        case 33: 
          { lexeme = yytext(); return FOR;
          }
        case 36: break;
        case 2: 
          { lexeme = yytext(); return ERRO;
          }
        case 37: break;
        case 13: 
          { lexeme = yytext(); return ATR;
          }
        case 38: break;
        case 7: 
          { lexeme = yytext(); return AP;
          }
        case 39: break;
        case 21: 
          { lexeme = yytext(); return IF;
          }
        case 40: break;
        case 18: 
          { lexeme = yytext(); return STRING;
          }
        case 41: break;
        case 30: 
          { lexeme = yytext(); return ELIF;
          }
        case 42: break;
        case 9: 
          { lexeme = yytext(); return ACH;
          }
        case 43: break;
        case 3: 
          { return ESPACO;
          }
        case 44: break;
        case 29: 
          { lexeme = yytext(); return BEGIN;
          }
        case 45: break;
        case 26: 
          { lexeme = yytext(); return ELSE;
          }
        case 46: break;
        case 19: 
          { lexeme = yytext(); return RD;
          }
        case 47: break;
        case 20: 
          { lexeme = yytext(); return ID;
          }
        case 48: break;
        case 12: 
          { lexeme = yytext(); return FC;
          }
        case 49: break;
        case 23: 
          { lexeme = yytext(); return OPLOG;
          }
        case 50: break;
        case 31: 
          { lexeme = yytext(); return END;
          }
        case 51: break;
        case 35: 
          { lexeme = yytext(); return BREAK;
          }
        case 52: break;
        case 4: 
          { lexeme = yytext(); return PLINHA;
          }
        case 53: break;
        case 17: 
          { lexeme = yytext(); return RECEIVE;
          }
        case 54: break;
        case 34: 
          { lexeme = yytext(); return FILE;
          }
        case 55: break;
        case 16: 
          { lexeme = yytext(); return BUSY;
          }
        case 56: break;
        case 11: 
          { lexeme = yytext(); return AC;
          }
        case 57: break;
        case 25: 
          { lexeme = yytext(); return STOP;
          }
        case 58: break;
        case 14: 
          { lexeme = yytext(); return VAR;
          }
        case 59: break;
        case 32: 
          { lexeme = yytext(); return WHILE;
          }
        case 60: break;
        case 28: 
          { lexeme = yytext(); return COMENT;
          }
        case 61: break;
        case 22: 
          { lexeme = yytext(); return SEND;
          }
        case 62: break;
        case 6: 
          { lexeme = yytext(); return OP;
          }
        case 63: break;
        case 8: 
          { lexeme = yytext(); return FP;
          }
        case 64: break;
        case 1: 
          { lexeme = yytext(); return NUM;
          }
        case 65: break;
        case 24: 
          { lexeme = yytext(); return START;
          }
        case 66: break;
        case 15: 
          { lexeme = yytext(); return SEPARADOR;
          }
        case 67: break;
        case 27: 
          { lexeme = yytext(); return WR;
          }
        case 68: break;
        case 5: 
          { lexeme = yytext(); return COMP;
          }
        case 69: break;
        case 10: 
          { lexeme = yytext(); return FCH;
          }
        case 70: break;
        default: 
          if (zzInput == YYEOF && zzStartRead == zzCurrentPos) {
            zzAtEOF = true;
            return null;
          } 
          else {
            zzScanError(ZZ_NO_MATCH);
          }
      }
    }
  }


}
