package AnaliseLexica;


public enum Token {
    OP,NUM,ATR,COMP,IF,ELSE,RD,WR,FOR,AP,FP,AC,FC,ACH,FCH,BEGIN,END,EOL,SEND,RECEIVE,START,STOP,BUSY,ID,COMENT
    ,STRING,ELIF,SEPARADOR,SUBROTINA,VAR,SPACE,ERRO,PLINHA,WHILE,OPLOG,EOF, ESPACO, QUEBRA_LINHA,FILE,BREAK;
}
