
//----------------------------------------------------
// The following code was generated by CUP v0.11a beta 20060608
// Mon May 20 20:00:45 BRT 2019
//----------------------------------------------------

package AnaliseSintatica;

/** CUP generated class containing symbol constants. */
public class sym {
  /* terminals */
  public static final int AC = 7;
  public static final int ATR = 13;
  public static final int COMENT = 33;
  public static final int BUSY = 27;
  public static final int SEPARADOR = 30;
  public static final int FOR = 31;
  public static final int FCH = 9;
  public static final int FP = 6;
  public static final int OP = 14;
  public static final int COMP = 15;
  public static final int BEGIN = 28;
  public static final int NUM = 11;
  public static final int PTV = 22;
  public static final int IF = 2;
  public static final int FC = 12;
  public static final int ID = 3;
  public static final int EOF = 0;
  public static final int RD = 20;
  public static final int error = 1;
  public static final int RECEIVE = 18;
  public static final int START = 24;
  public static final int BREAK = 35;
  public static final int ELSE = 4;
  public static final int STOP = 25;
  public static final int WR = 21;
  public static final int FILE = 32;
  public static final int WHILE = 19;
  public static final int END = 23;
  public static final int ACH = 8;
  public static final int STRING = 10;
  public static final int OPLOG = 29;
  public static final int SEND = 17;
  public static final int AP = 5;
  public static final int SUB = 26;
  public static final int VAR = 16;
  public static final int ELIF = 34;
}

